[package]
name = "knapsack"
version = "0.1.0"
authors = ["Takuya Akiba <t.akiba.65536@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
glob = "0.3.0"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "problem_sizes"
path = "src/problem_sizes_main.rs"

