[package]
name = "proto"
version = "0.1.0"
authors = ["Unagi"]

[dependencies]
futures = "0.1.16"
grpcio = { version = "0.4.4", default-features = false, features = ["protobuf-codec"] }
protobuf = "2.6.2"

[build-dependencies]
protoc-grpcio = "1.0.2"
