// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Api_Request_InsertSolution_Strategy int32

const (
	// 既存のフィールドはリジャッジしません
	Api_Request_InsertSolution_IGNORE Api_Request_InsertSolution_Strategy = 0
	// 既存のものもリジャッジします
	Api_Request_InsertSolution_REPLACE Api_Request_InsertSolution_Strategy = 1
)

var Api_Request_InsertSolution_Strategy_name = map[int32]string{
	0: "IGNORE",
	1: "REPLACE",
}

var Api_Request_InsertSolution_Strategy_value = map[string]int32{
	"IGNORE":  0,
	"REPLACE": 1,
}

func (x Api_Request_InsertSolution_Strategy) String() string {
	return proto.EnumName(Api_Request_InsertSolution_Strategy_name, int32(x))
}

func (Api_Request_InsertSolution_Strategy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0, 4, 0}
}

type Api struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api) Reset()         { *m = Api{} }
func (m *Api) String() string { return proto.CompactTextString(m) }
func (*Api) ProtoMessage()    {}
func (*Api) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *Api) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api.Unmarshal(m, b)
}
func (m *Api) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api.Marshal(b, m, deterministic)
}
func (m *Api) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api.Merge(m, src)
}
func (m *Api) XXX_Size() int {
	return xxx_messageInfo_Api.Size(m)
}
func (m *Api) XXX_DiscardUnknown() {
	xxx_messageInfo_Api.DiscardUnknown(m)
}

var xxx_messageInfo_Api proto.InternalMessageInfo

// API Request defition.
//
// NEXT ID TO USE: 2
type Api_Request struct {
	Context              *Api_Request_Context         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	InsertProblem        *Api_Request_InsertProblem   `protobuf:"bytes,2,opt,name=insert_problem,json=insertProblem,proto3" json:"insert_problem,omitempty"`
	InsertProgram        *Api_Request_InsertProgram   `protobuf:"bytes,3,opt,name=insert_program,json=insertProgram,proto3" json:"insert_program,omitempty"`
	AcquireSolution      *Api_Request_AcquireSolution `protobuf:"bytes,4,opt,name=acquire_solution,json=acquireSolution,proto3" json:"acquire_solution,omitempty"`
	InsertSolution       *Api_Request_InsertSolution  `protobuf:"bytes,6,opt,name=insert_solution,json=insertSolution,proto3" json:"insert_solution,omitempty"`
	UpdateSolution       *Api_Request_UpdateSolution  `protobuf:"bytes,5,opt,name=update_solution,json=updateSolution,proto3" json:"update_solution,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *Api_Request) Reset()         { *m = Api_Request{} }
func (m *Api_Request) String() string { return proto.CompactTextString(m) }
func (*Api_Request) ProtoMessage()    {}
func (*Api_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0}
}

func (m *Api_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Request.Unmarshal(m, b)
}
func (m *Api_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Request.Marshal(b, m, deterministic)
}
func (m *Api_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Request.Merge(m, src)
}
func (m *Api_Request) XXX_Size() int {
	return xxx_messageInfo_Api_Request.Size(m)
}
func (m *Api_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Request proto.InternalMessageInfo

func (m *Api_Request) GetContext() *Api_Request_Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Api_Request) GetInsertProblem() *Api_Request_InsertProblem {
	if m != nil {
		return m.InsertProblem
	}
	return nil
}

func (m *Api_Request) GetInsertProgram() *Api_Request_InsertProgram {
	if m != nil {
		return m.InsertProgram
	}
	return nil
}

func (m *Api_Request) GetAcquireSolution() *Api_Request_AcquireSolution {
	if m != nil {
		return m.AcquireSolution
	}
	return nil
}

func (m *Api_Request) GetInsertSolution() *Api_Request_InsertSolution {
	if m != nil {
		return m.InsertSolution
	}
	return nil
}

func (m *Api_Request) GetUpdateSolution() *Api_Request_UpdateSolution {
	if m != nil {
		return m.UpdateSolution
	}
	return nil
}

type Api_Request_Context struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Request_Context) Reset()         { *m = Api_Request_Context{} }
func (m *Api_Request_Context) String() string { return proto.CompactTextString(m) }
func (*Api_Request_Context) ProtoMessage()    {}
func (*Api_Request_Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0, 0}
}

func (m *Api_Request_Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Request_Context.Unmarshal(m, b)
}
func (m *Api_Request_Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Request_Context.Marshal(b, m, deterministic)
}
func (m *Api_Request_Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Request_Context.Merge(m, src)
}
func (m *Api_Request_Context) XXX_Size() int {
	return xxx_messageInfo_Api_Request_Context.Size(m)
}
func (m *Api_Request_Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Request_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Request_Context proto.InternalMessageInfo

// 問題の追加を行います
type Api_Request_InsertProblem struct {
	ProblemName          string   `protobuf:"bytes,1,opt,name=problem_name,json=problemName,proto3" json:"problem_name,omitempty"`
	ProblemData          []byte   `protobuf:"bytes,2,opt,name=problem_data,json=problemData,proto3" json:"problem_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Request_InsertProblem) Reset()         { *m = Api_Request_InsertProblem{} }
func (m *Api_Request_InsertProblem) String() string { return proto.CompactTextString(m) }
func (*Api_Request_InsertProblem) ProtoMessage()    {}
func (*Api_Request_InsertProblem) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0, 1}
}

func (m *Api_Request_InsertProblem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Request_InsertProblem.Unmarshal(m, b)
}
func (m *Api_Request_InsertProblem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Request_InsertProblem.Marshal(b, m, deterministic)
}
func (m *Api_Request_InsertProblem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Request_InsertProblem.Merge(m, src)
}
func (m *Api_Request_InsertProblem) XXX_Size() int {
	return xxx_messageInfo_Api_Request_InsertProblem.Size(m)
}
func (m *Api_Request_InsertProblem) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Request_InsertProblem.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Request_InsertProblem proto.InternalMessageInfo

func (m *Api_Request_InsertProblem) GetProblemName() string {
	if m != nil {
		return m.ProblemName
	}
	return ""
}

func (m *Api_Request_InsertProblem) GetProblemData() []byte {
	if m != nil {
		return m.ProblemData
	}
	return nil
}

// AIプログラムの追加を行います
type Api_Request_InsertProgram struct {
	ProgramName          string   `protobuf:"bytes,1,opt,name=program_name,json=programName,proto3" json:"program_name,omitempty"`
	ProgramCode          string   `protobuf:"bytes,2,opt,name=program_code,json=programCode,proto3" json:"program_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Request_InsertProgram) Reset()         { *m = Api_Request_InsertProgram{} }
func (m *Api_Request_InsertProgram) String() string { return proto.CompactTextString(m) }
func (*Api_Request_InsertProgram) ProtoMessage()    {}
func (*Api_Request_InsertProgram) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0, 2}
}

func (m *Api_Request_InsertProgram) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Request_InsertProgram.Unmarshal(m, b)
}
func (m *Api_Request_InsertProgram) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Request_InsertProgram.Marshal(b, m, deterministic)
}
func (m *Api_Request_InsertProgram) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Request_InsertProgram.Merge(m, src)
}
func (m *Api_Request_InsertProgram) XXX_Size() int {
	return xxx_messageInfo_Api_Request_InsertProgram.Size(m)
}
func (m *Api_Request_InsertProgram) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Request_InsertProgram.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Request_InsertProgram proto.InternalMessageInfo

func (m *Api_Request_InsertProgram) GetProgramName() string {
	if m != nil {
		return m.ProgramName
	}
	return ""
}

func (m *Api_Request_InsertProgram) GetProgramCode() string {
	if m != nil {
		return m.ProgramCode
	}
	return ""
}

// ジャッジプログラムが実行対象をこのメソッドで確保します
type Api_Request_AcquireSolution struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Request_AcquireSolution) Reset()         { *m = Api_Request_AcquireSolution{} }
func (m *Api_Request_AcquireSolution) String() string { return proto.CompactTextString(m) }
func (*Api_Request_AcquireSolution) ProtoMessage()    {}
func (*Api_Request_AcquireSolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0, 3}
}

func (m *Api_Request_AcquireSolution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Request_AcquireSolution.Unmarshal(m, b)
}
func (m *Api_Request_AcquireSolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Request_AcquireSolution.Marshal(b, m, deterministic)
}
func (m *Api_Request_AcquireSolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Request_AcquireSolution.Merge(m, src)
}
func (m *Api_Request_AcquireSolution) XXX_Size() int {
	return xxx_messageInfo_Api_Request_AcquireSolution.Size(m)
}
func (m *Api_Request_AcquireSolution) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Request_AcquireSolution.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Request_AcquireSolution proto.InternalMessageInfo

// リジャッジを行います
type Api_Request_InsertSolution struct {
	Strategy             Api_Request_InsertSolution_Strategy `protobuf:"varint,1,opt,name=strategy,proto3,enum=pb.Api_Request_InsertSolution_Strategy" json:"strategy,omitempty"`
	ProgramId            int64                               `protobuf:"varint,2,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	ProblemId            int64                               `protobuf:"varint,3,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *Api_Request_InsertSolution) Reset()         { *m = Api_Request_InsertSolution{} }
func (m *Api_Request_InsertSolution) String() string { return proto.CompactTextString(m) }
func (*Api_Request_InsertSolution) ProtoMessage()    {}
func (*Api_Request_InsertSolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0, 4}
}

func (m *Api_Request_InsertSolution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Request_InsertSolution.Unmarshal(m, b)
}
func (m *Api_Request_InsertSolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Request_InsertSolution.Marshal(b, m, deterministic)
}
func (m *Api_Request_InsertSolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Request_InsertSolution.Merge(m, src)
}
func (m *Api_Request_InsertSolution) XXX_Size() int {
	return xxx_messageInfo_Api_Request_InsertSolution.Size(m)
}
func (m *Api_Request_InsertSolution) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Request_InsertSolution.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Request_InsertSolution proto.InternalMessageInfo

func (m *Api_Request_InsertSolution) GetStrategy() Api_Request_InsertSolution_Strategy {
	if m != nil {
		return m.Strategy
	}
	return Api_Request_InsertSolution_IGNORE
}

func (m *Api_Request_InsertSolution) GetProgramId() int64 {
	if m != nil {
		return m.ProgramId
	}
	return 0
}

func (m *Api_Request_InsertSolution) GetProblemId() int64 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

// スコアの更新を行います
type Api_Request_UpdateSolution struct {
	SolutionId           int64    `protobuf:"varint,1,opt,name=solution_id,json=solutionId,proto3" json:"solution_id,omitempty"`
	SolutionScore        int64    `protobuf:"varint,2,opt,name=solution_score,json=solutionScore,proto3" json:"solution_score,omitempty"`
	SolutionDataBlob     []byte   `protobuf:"bytes,3,opt,name=solution_data_blob,json=solutionDataBlob,proto3" json:"solution_data_blob,omitempty"`
	SolutionDataError    []byte   `protobuf:"bytes,4,opt,name=solution_data_error,json=solutionDataError,proto3" json:"solution_data_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Request_UpdateSolution) Reset()         { *m = Api_Request_UpdateSolution{} }
func (m *Api_Request_UpdateSolution) String() string { return proto.CompactTextString(m) }
func (*Api_Request_UpdateSolution) ProtoMessage()    {}
func (*Api_Request_UpdateSolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0, 5}
}

func (m *Api_Request_UpdateSolution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Request_UpdateSolution.Unmarshal(m, b)
}
func (m *Api_Request_UpdateSolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Request_UpdateSolution.Marshal(b, m, deterministic)
}
func (m *Api_Request_UpdateSolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Request_UpdateSolution.Merge(m, src)
}
func (m *Api_Request_UpdateSolution) XXX_Size() int {
	return xxx_messageInfo_Api_Request_UpdateSolution.Size(m)
}
func (m *Api_Request_UpdateSolution) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Request_UpdateSolution.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Request_UpdateSolution proto.InternalMessageInfo

func (m *Api_Request_UpdateSolution) GetSolutionId() int64 {
	if m != nil {
		return m.SolutionId
	}
	return 0
}

func (m *Api_Request_UpdateSolution) GetSolutionScore() int64 {
	if m != nil {
		return m.SolutionScore
	}
	return 0
}

func (m *Api_Request_UpdateSolution) GetSolutionDataBlob() []byte {
	if m != nil {
		return m.SolutionDataBlob
	}
	return nil
}

func (m *Api_Request_UpdateSolution) GetSolutionDataError() []byte {
	if m != nil {
		return m.SolutionDataError
	}
	return nil
}

// API Response defition.
//
// NEXT ID TO USE: 2
type Api_Response struct {
	Context              *Api_Response_Context         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	InsertProblem        *Api_Response_InsertProblem   `protobuf:"bytes,2,opt,name=insert_problem,json=insertProblem,proto3" json:"insert_problem,omitempty"`
	InsertProgram        *Api_Response_InsertProgram   `protobuf:"bytes,3,opt,name=insert_program,json=insertProgram,proto3" json:"insert_program,omitempty"`
	AcquireSolution      *Api_Response_AcquireSolution `protobuf:"bytes,4,opt,name=acquire_solution,json=acquireSolution,proto3" json:"acquire_solution,omitempty"`
	InsertSolution       *Api_Response_InsertSolution  `protobuf:"bytes,6,opt,name=insert_solution,json=insertSolution,proto3" json:"insert_solution,omitempty"`
	UpdateSolution       *Api_Response_UpdateSolution  `protobuf:"bytes,5,opt,name=update_solution,json=updateSolution,proto3" json:"update_solution,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Api_Response) Reset()         { *m = Api_Response{} }
func (m *Api_Response) String() string { return proto.CompactTextString(m) }
func (*Api_Response) ProtoMessage()    {}
func (*Api_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 1}
}

func (m *Api_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Response.Unmarshal(m, b)
}
func (m *Api_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Response.Marshal(b, m, deterministic)
}
func (m *Api_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Response.Merge(m, src)
}
func (m *Api_Response) XXX_Size() int {
	return xxx_messageInfo_Api_Response.Size(m)
}
func (m *Api_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Response proto.InternalMessageInfo

func (m *Api_Response) GetContext() *Api_Response_Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Api_Response) GetInsertProblem() *Api_Response_InsertProblem {
	if m != nil {
		return m.InsertProblem
	}
	return nil
}

func (m *Api_Response) GetInsertProgram() *Api_Response_InsertProgram {
	if m != nil {
		return m.InsertProgram
	}
	return nil
}

func (m *Api_Response) GetAcquireSolution() *Api_Response_AcquireSolution {
	if m != nil {
		return m.AcquireSolution
	}
	return nil
}

func (m *Api_Response) GetInsertSolution() *Api_Response_InsertSolution {
	if m != nil {
		return m.InsertSolution
	}
	return nil
}

func (m *Api_Response) GetUpdateSolution() *Api_Response_UpdateSolution {
	if m != nil {
		return m.UpdateSolution
	}
	return nil
}

type Api_Response_Context struct {
	ErrorMessages        []string `protobuf:"bytes,1,rep,name=error_messages,json=errorMessages,proto3" json:"error_messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Response_Context) Reset()         { *m = Api_Response_Context{} }
func (m *Api_Response_Context) String() string { return proto.CompactTextString(m) }
func (*Api_Response_Context) ProtoMessage()    {}
func (*Api_Response_Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 1, 0}
}

func (m *Api_Response_Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Response_Context.Unmarshal(m, b)
}
func (m *Api_Response_Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Response_Context.Marshal(b, m, deterministic)
}
func (m *Api_Response_Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Response_Context.Merge(m, src)
}
func (m *Api_Response_Context) XXX_Size() int {
	return xxx_messageInfo_Api_Response_Context.Size(m)
}
func (m *Api_Response_Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Response_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Response_Context proto.InternalMessageInfo

func (m *Api_Response_Context) GetErrorMessages() []string {
	if m != nil {
		return m.ErrorMessages
	}
	return nil
}

type Api_Response_InsertProblem struct {
	ProblemId            int64    `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Response_InsertProblem) Reset()         { *m = Api_Response_InsertProblem{} }
func (m *Api_Response_InsertProblem) String() string { return proto.CompactTextString(m) }
func (*Api_Response_InsertProblem) ProtoMessage()    {}
func (*Api_Response_InsertProblem) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 1, 1}
}

func (m *Api_Response_InsertProblem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Response_InsertProblem.Unmarshal(m, b)
}
func (m *Api_Response_InsertProblem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Response_InsertProblem.Marshal(b, m, deterministic)
}
func (m *Api_Response_InsertProblem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Response_InsertProblem.Merge(m, src)
}
func (m *Api_Response_InsertProblem) XXX_Size() int {
	return xxx_messageInfo_Api_Response_InsertProblem.Size(m)
}
func (m *Api_Response_InsertProblem) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Response_InsertProblem.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Response_InsertProblem proto.InternalMessageInfo

func (m *Api_Response_InsertProblem) GetProblemId() int64 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

type Api_Response_InsertProgram struct {
	ProgramId            int64    `protobuf:"varint,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Response_InsertProgram) Reset()         { *m = Api_Response_InsertProgram{} }
func (m *Api_Response_InsertProgram) String() string { return proto.CompactTextString(m) }
func (*Api_Response_InsertProgram) ProtoMessage()    {}
func (*Api_Response_InsertProgram) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 1, 2}
}

func (m *Api_Response_InsertProgram) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Response_InsertProgram.Unmarshal(m, b)
}
func (m *Api_Response_InsertProgram) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Response_InsertProgram.Marshal(b, m, deterministic)
}
func (m *Api_Response_InsertProgram) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Response_InsertProgram.Merge(m, src)
}
func (m *Api_Response_InsertProgram) XXX_Size() int {
	return xxx_messageInfo_Api_Response_InsertProgram.Size(m)
}
func (m *Api_Response_InsertProgram) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Response_InsertProgram.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Response_InsertProgram proto.InternalMessageInfo

func (m *Api_Response_InsertProgram) GetProgramId() int64 {
	if m != nil {
		return m.ProgramId
	}
	return 0
}

type Api_Response_AcquireSolution struct {
	SolutionId           int64    `protobuf:"varint,1,opt,name=solution_id,json=solutionId,proto3" json:"solution_id,omitempty"`
	ProgramId            int64    `protobuf:"varint,2,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	ProgramName          string   `protobuf:"bytes,3,opt,name=program_name,json=programName,proto3" json:"program_name,omitempty"`
	ProgramCode          string   `protobuf:"bytes,4,opt,name=program_code,json=programCode,proto3" json:"program_code,omitempty"`
	ProblemId            int64    `protobuf:"varint,5,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	ProblemName          string   `protobuf:"bytes,6,opt,name=problem_name,json=problemName,proto3" json:"problem_name,omitempty"`
	ProblemDataBlob      []byte   `protobuf:"bytes,7,opt,name=problem_data_blob,json=problemDataBlob,proto3" json:"problem_data_blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Response_AcquireSolution) Reset()         { *m = Api_Response_AcquireSolution{} }
func (m *Api_Response_AcquireSolution) String() string { return proto.CompactTextString(m) }
func (*Api_Response_AcquireSolution) ProtoMessage()    {}
func (*Api_Response_AcquireSolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 1, 3}
}

func (m *Api_Response_AcquireSolution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Response_AcquireSolution.Unmarshal(m, b)
}
func (m *Api_Response_AcquireSolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Response_AcquireSolution.Marshal(b, m, deterministic)
}
func (m *Api_Response_AcquireSolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Response_AcquireSolution.Merge(m, src)
}
func (m *Api_Response_AcquireSolution) XXX_Size() int {
	return xxx_messageInfo_Api_Response_AcquireSolution.Size(m)
}
func (m *Api_Response_AcquireSolution) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Response_AcquireSolution.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Response_AcquireSolution proto.InternalMessageInfo

func (m *Api_Response_AcquireSolution) GetSolutionId() int64 {
	if m != nil {
		return m.SolutionId
	}
	return 0
}

func (m *Api_Response_AcquireSolution) GetProgramId() int64 {
	if m != nil {
		return m.ProgramId
	}
	return 0
}

func (m *Api_Response_AcquireSolution) GetProgramName() string {
	if m != nil {
		return m.ProgramName
	}
	return ""
}

func (m *Api_Response_AcquireSolution) GetProgramCode() string {
	if m != nil {
		return m.ProgramCode
	}
	return ""
}

func (m *Api_Response_AcquireSolution) GetProblemId() int64 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

func (m *Api_Response_AcquireSolution) GetProblemName() string {
	if m != nil {
		return m.ProblemName
	}
	return ""
}

func (m *Api_Response_AcquireSolution) GetProblemDataBlob() []byte {
	if m != nil {
		return m.ProblemDataBlob
	}
	return nil
}

type Api_Response_InsertSolution struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Response_InsertSolution) Reset()         { *m = Api_Response_InsertSolution{} }
func (m *Api_Response_InsertSolution) String() string { return proto.CompactTextString(m) }
func (*Api_Response_InsertSolution) ProtoMessage()    {}
func (*Api_Response_InsertSolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 1, 4}
}

func (m *Api_Response_InsertSolution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Response_InsertSolution.Unmarshal(m, b)
}
func (m *Api_Response_InsertSolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Response_InsertSolution.Marshal(b, m, deterministic)
}
func (m *Api_Response_InsertSolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Response_InsertSolution.Merge(m, src)
}
func (m *Api_Response_InsertSolution) XXX_Size() int {
	return xxx_messageInfo_Api_Response_InsertSolution.Size(m)
}
func (m *Api_Response_InsertSolution) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Response_InsertSolution.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Response_InsertSolution proto.InternalMessageInfo

type Api_Response_UpdateSolution struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Response_UpdateSolution) Reset()         { *m = Api_Response_UpdateSolution{} }
func (m *Api_Response_UpdateSolution) String() string { return proto.CompactTextString(m) }
func (*Api_Response_UpdateSolution) ProtoMessage()    {}
func (*Api_Response_UpdateSolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 1, 5}
}

func (m *Api_Response_UpdateSolution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Response_UpdateSolution.Unmarshal(m, b)
}
func (m *Api_Response_UpdateSolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Response_UpdateSolution.Marshal(b, m, deterministic)
}
func (m *Api_Response_UpdateSolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Response_UpdateSolution.Merge(m, src)
}
func (m *Api_Response_UpdateSolution) XXX_Size() int {
	return xxx_messageInfo_Api_Response_UpdateSolution.Size(m)
}
func (m *Api_Response_UpdateSolution) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Response_UpdateSolution.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Response_UpdateSolution proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pb.Api_Request_InsertSolution_Strategy", Api_Request_InsertSolution_Strategy_name, Api_Request_InsertSolution_Strategy_value)
	proto.RegisterType((*Api)(nil), "pb.Api")
	proto.RegisterType((*Api_Request)(nil), "pb.Api.Request")
	proto.RegisterType((*Api_Request_Context)(nil), "pb.Api.Request.Context")
	proto.RegisterType((*Api_Request_InsertProblem)(nil), "pb.Api.Request.InsertProblem")
	proto.RegisterType((*Api_Request_InsertProgram)(nil), "pb.Api.Request.InsertProgram")
	proto.RegisterType((*Api_Request_AcquireSolution)(nil), "pb.Api.Request.AcquireSolution")
	proto.RegisterType((*Api_Request_InsertSolution)(nil), "pb.Api.Request.InsertSolution")
	proto.RegisterType((*Api_Request_UpdateSolution)(nil), "pb.Api.Request.UpdateSolution")
	proto.RegisterType((*Api_Response)(nil), "pb.Api.Response")
	proto.RegisterType((*Api_Response_Context)(nil), "pb.Api.Response.Context")
	proto.RegisterType((*Api_Response_InsertProblem)(nil), "pb.Api.Response.InsertProblem")
	proto.RegisterType((*Api_Response_InsertProgram)(nil), "pb.Api.Response.InsertProgram")
	proto.RegisterType((*Api_Response_AcquireSolution)(nil), "pb.Api.Response.AcquireSolution")
	proto.RegisterType((*Api_Response_InsertSolution)(nil), "pb.Api.Response.InsertSolution")
	proto.RegisterType((*Api_Response_UpdateSolution)(nil), "pb.Api.Response.UpdateSolution")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 641 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xdd, 0x6e, 0xda, 0x4c,
	0x10, 0xfd, 0x1c, 0x12, 0x1c, 0x06, 0x30, 0x64, 0xbf, 0x8b, 0x5a, 0x96, 0xf2, 0xd3, 0x54, 0x55,
	0xa3, 0xaa, 0xb2, 0xda, 0xf4, 0x09, 0x28, 0xb1, 0x12, 0xfa, 0x93, 0x46, 0x8b, 0x72, 0x8d, 0xd6,
	0x78, 0x85, 0x2c, 0x01, 0xeb, 0xd8, 0x46, 0x6a, 0x1f, 0xa0, 0xaf, 0x54, 0xf5, 0x61, 0x7a, 0xdd,
	0x9b, 0xbe, 0x44, 0xb5, 0xeb, 0xb5, 0xf1, 0xae, 0x31, 0xbe, 0x63, 0xcf, 0x9e, 0x39, 0xcc, 0xce,
	0xcc, 0x19, 0x03, 0x04, 0x24, 0x25, 0x6e, 0x14, 0xb3, 0x94, 0xa1, 0x83, 0xc8, 0xbf, 0xfc, 0x6d,
	0x41, 0x6b, 0x14, 0x85, 0xce, 0x1f, 0x13, 0x4c, 0x4c, 0x9f, 0x36, 0x34, 0x49, 0xd1, 0x3b, 0x30,
	0xe7, 0x6c, 0x9d, 0xd2, 0x6f, 0xa9, 0x6d, 0x5c, 0x18, 0x57, 0xdd, 0xeb, 0x67, 0x6e, 0xe4, 0xbb,
	0xa3, 0x28, 0x74, 0x25, 0xc3, 0x1d, 0x67, 0xd7, 0x38, 0xe7, 0xa1, 0x1b, 0xb0, 0xc2, 0x75, 0x42,
	0xe3, 0x74, 0x16, 0xc5, 0xcc, 0x5f, 0xd2, 0x95, 0x7d, 0x20, 0x22, 0x4f, 0xf5, 0xc8, 0x89, 0x60,
	0x3d, 0x64, 0x24, 0xdc, 0x0f, 0xcb, 0x47, 0x55, 0x65, 0x11, 0x93, 0x95, 0xdd, 0x6a, 0x50, 0xe1,
	0xa4, 0x92, 0x0a, 0x3f, 0xa2, 0x8f, 0x30, 0x24, 0xf3, 0xa7, 0x4d, 0x18, 0xd3, 0x59, 0xc2, 0x96,
	0x9b, 0x34, 0x64, 0x6b, 0xfb, 0x50, 0xe8, 0x9c, 0xeb, 0x3a, 0xa3, 0x8c, 0x37, 0x95, 0x34, 0x3c,
	0x20, 0x2a, 0x80, 0x6e, 0x61, 0x20, 0x33, 0x2a, 0xa4, 0xda, 0x42, 0xea, 0x6c, 0x77, 0x4a, 0x85,
	0x92, 0x7c, 0x48, 0x59, 0x68, 0x13, 0x05, 0x24, 0x2d, 0xe5, 0x74, 0xb4, 0x5b, 0xe8, 0x51, 0xd0,
	0xb6, 0x42, 0x1b, 0xe5, 0xec, 0x74, 0xc0, 0x94, 0xd5, 0x77, 0x1e, 0xa1, 0xaf, 0x94, 0x13, 0x3d,
	0x87, 0x9e, 0x2c, 0xff, 0x6c, 0x4d, 0x56, 0x54, 0x74, 0xaf, 0x83, 0xbb, 0x12, 0xbb, 0x27, 0x2b,
	0x5a, 0xa6, 0xf0, 0x49, 0x10, 0x6d, 0xea, 0x15, 0x94, 0x1b, 0x92, 0x12, 0x45, 0x56, 0x14, 0x34,
	0x8b, 0xe1, 0x3f, 0x75, 0x59, 0x8e, 0x95, 0x64, 0x05, 0x65, 0xce, 0x02, 0x2a, 0x64, 0xb7, 0x94,
	0x31, 0x0b, 0xa8, 0x73, 0x02, 0x03, 0xad, 0xdc, 0xce, 0x2f, 0x03, 0x2c, 0xb5, 0x6e, 0x68, 0x0c,
	0xc7, 0x49, 0x1a, 0x93, 0x94, 0x2e, 0xbe, 0x8b, 0xff, 0xb1, 0xae, 0x5f, 0xed, 0xaf, 0xb4, 0x3b,
	0x95, 0x74, 0x5c, 0x04, 0xa2, 0x53, 0x80, 0x3c, 0x9b, 0x30, 0x10, 0xb9, 0xb4, 0x70, 0x47, 0x22,
	0x93, 0x40, 0x5e, 0x8b, 0x1a, 0x84, 0x81, 0x18, 0xb1, 0xec, 0x9a, 0x23, 0x93, 0xe0, 0xf2, 0x05,
	0x1c, 0xe7, 0x9a, 0x08, 0xa0, 0x3d, 0xb9, 0xbd, 0xff, 0x8a, 0xbd, 0xe1, 0x7f, 0xa8, 0x0b, 0x26,
	0xf6, 0x1e, 0x3e, 0x8f, 0xc6, 0xde, 0xd0, 0x70, 0x7e, 0x1a, 0x60, 0xa9, 0x9d, 0x42, 0xe7, 0xd0,
	0xcd, 0x7b, 0xcb, 0x75, 0x0d, 0xa1, 0x0b, 0x39, 0x34, 0x09, 0xd0, 0x4b, 0xb0, 0x0a, 0x42, 0x32,
	0x67, 0x31, 0x95, 0xa9, 0xf5, 0x73, 0x74, 0xca, 0x41, 0xf4, 0x06, 0x50, 0x41, 0xe3, 0x3d, 0x9a,
	0xf9, 0x4b, 0xe6, 0x8b, 0x34, 0x7b, 0x78, 0x98, 0xdf, 0xf0, 0x4e, 0x7d, 0x58, 0x32, 0x1f, 0xb9,
	0xf0, 0xbf, 0xca, 0xa6, 0x71, 0xcc, 0x62, 0x31, 0xf0, 0x3d, 0x7c, 0x52, 0xa6, 0x7b, 0xfc, 0xc2,
	0xf9, 0xdb, 0x86, 0x63, 0x4c, 0x93, 0x88, 0xad, 0x13, 0x8a, 0xae, 0x75, 0xa7, 0xdb, 0xdb, 0x62,
	0x67, 0x94, 0xaa, 0xd5, 0xbd, 0x1a, 0xab, 0x9f, 0x55, 0x42, 0xf7, 0x7a, 0xdd, 0xab, 0xf1, 0xfa,
	0x1e, 0x99, 0x5d, 0x66, 0xff, 0x54, 0x6b, 0xf6, 0x8b, 0x8a, 0x50, 0xa3, 0xdb, 0xef, 0xea, 0xdc,
	0x7e, 0x5e, 0x93, 0x54, 0xad, 0xdd, 0xef, 0xea, 0xec, 0x5e, 0x55, 0x6a, 0xf0, 0xfb, 0xdb, 0xc2,
	0xef, 0x7c, 0x7e, 0x44, 0x73, 0x67, 0x2b, 0x9a, 0x24, 0x64, 0x41, 0x13, 0xdb, 0xb8, 0x68, 0x5d,
	0x75, 0x70, 0x5f, 0xa0, 0x5f, 0x24, 0xe8, 0xb8, 0xfa, 0x5a, 0x50, 0xe7, 0xdd, 0xd0, 0xe6, 0x5d,
	0xe1, 0x8b, 0x9a, 0xaa, 0xf6, 0x31, 0x34, 0xfb, 0x38, 0x3f, 0x0e, 0x2a, 0x4e, 0x6e, 0x9e, 0xfd,
	0x06, 0x4b, 0xea, 0x2b, 0xa6, 0xd5, 0xbc, 0x62, 0x0e, 0x2b, 0x2b, 0x46, 0x7b, 0xe8, 0x91, 0xf6,
	0xd0, 0xca, 0x7a, 0x6c, 0x57, 0xd7, 0xe3, 0x6b, 0x38, 0x29, 0xaf, 0xc7, 0xcc, 0x7a, 0xa6, 0xf0,
	0xd2, 0xa0, 0xb4, 0x23, 0xb9, 0xf3, 0x9c, 0xa1, 0xbe, 0xbc, 0x38, 0xa2, 0x76, 0xd3, 0x6f, 0x8b,
	0x2f, 0xed, 0xfb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xd2, 0xf4, 0xef, 0x77, 0x07, 0x00,
	0x00,
}
