// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Api struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api) Reset()         { *m = Api{} }
func (m *Api) String() string { return proto.CompactTextString(m) }
func (*Api) ProtoMessage()    {}
func (*Api) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *Api) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api.Unmarshal(m, b)
}
func (m *Api) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api.Marshal(b, m, deterministic)
}
func (m *Api) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api.Merge(m, src)
}
func (m *Api) XXX_Size() int {
	return xxx_messageInfo_Api.Size(m)
}
func (m *Api) XXX_DiscardUnknown() {
	xxx_messageInfo_Api.DiscardUnknown(m)
}

var xxx_messageInfo_Api proto.InternalMessageInfo

// API Request defition.
//
// NEXT ID TO USE: 2
type Api_Request struct {
	Context              *Api_Request_Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	InsertProblem        *Api_Request_InsertProblem `protobuf:"bytes,2,opt,name=insert_problem,json=insertProblem,proto3" json:"insert_problem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Api_Request) Reset()         { *m = Api_Request{} }
func (m *Api_Request) String() string { return proto.CompactTextString(m) }
func (*Api_Request) ProtoMessage()    {}
func (*Api_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0}
}

func (m *Api_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Request.Unmarshal(m, b)
}
func (m *Api_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Request.Marshal(b, m, deterministic)
}
func (m *Api_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Request.Merge(m, src)
}
func (m *Api_Request) XXX_Size() int {
	return xxx_messageInfo_Api_Request.Size(m)
}
func (m *Api_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Request proto.InternalMessageInfo

func (m *Api_Request) GetContext() *Api_Request_Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Api_Request) GetInsertProblem() *Api_Request_InsertProblem {
	if m != nil {
		return m.InsertProblem
	}
	return nil
}

type Api_Request_Context struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Request_Context) Reset()         { *m = Api_Request_Context{} }
func (m *Api_Request_Context) String() string { return proto.CompactTextString(m) }
func (*Api_Request_Context) ProtoMessage()    {}
func (*Api_Request_Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0, 0}
}

func (m *Api_Request_Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Request_Context.Unmarshal(m, b)
}
func (m *Api_Request_Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Request_Context.Marshal(b, m, deterministic)
}
func (m *Api_Request_Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Request_Context.Merge(m, src)
}
func (m *Api_Request_Context) XXX_Size() int {
	return xxx_messageInfo_Api_Request_Context.Size(m)
}
func (m *Api_Request_Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Request_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Request_Context proto.InternalMessageInfo

type Api_Request_InsertProblem struct {
	ProblemName          string   `protobuf:"bytes,1,opt,name=problem_name,json=problemName,proto3" json:"problem_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Request_InsertProblem) Reset()         { *m = Api_Request_InsertProblem{} }
func (m *Api_Request_InsertProblem) String() string { return proto.CompactTextString(m) }
func (*Api_Request_InsertProblem) ProtoMessage()    {}
func (*Api_Request_InsertProblem) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0, 1}
}

func (m *Api_Request_InsertProblem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Request_InsertProblem.Unmarshal(m, b)
}
func (m *Api_Request_InsertProblem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Request_InsertProblem.Marshal(b, m, deterministic)
}
func (m *Api_Request_InsertProblem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Request_InsertProblem.Merge(m, src)
}
func (m *Api_Request_InsertProblem) XXX_Size() int {
	return xxx_messageInfo_Api_Request_InsertProblem.Size(m)
}
func (m *Api_Request_InsertProblem) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Request_InsertProblem.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Request_InsertProblem proto.InternalMessageInfo

func (m *Api_Request_InsertProblem) GetProblemName() string {
	if m != nil {
		return m.ProblemName
	}
	return ""
}

// API Response defition.
//
// NEXT ID TO USE: 2
type Api_Response struct {
	Context              *Api_Response_Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	InsertProblem        *Api_Response_InsertProblem `protobuf:"bytes,2,opt,name=insert_problem,json=insertProblem,proto3" json:"insert_problem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Api_Response) Reset()         { *m = Api_Response{} }
func (m *Api_Response) String() string { return proto.CompactTextString(m) }
func (*Api_Response) ProtoMessage()    {}
func (*Api_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 1}
}

func (m *Api_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Response.Unmarshal(m, b)
}
func (m *Api_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Response.Marshal(b, m, deterministic)
}
func (m *Api_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Response.Merge(m, src)
}
func (m *Api_Response) XXX_Size() int {
	return xxx_messageInfo_Api_Response.Size(m)
}
func (m *Api_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Response proto.InternalMessageInfo

func (m *Api_Response) GetContext() *Api_Response_Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Api_Response) GetInsertProblem() *Api_Response_InsertProblem {
	if m != nil {
		return m.InsertProblem
	}
	return nil
}

type Api_Response_Context struct {
	ErrorMessages        []string `protobuf:"bytes,1,rep,name=error_messages,json=errorMessages,proto3" json:"error_messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Response_Context) Reset()         { *m = Api_Response_Context{} }
func (m *Api_Response_Context) String() string { return proto.CompactTextString(m) }
func (*Api_Response_Context) ProtoMessage()    {}
func (*Api_Response_Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 1, 0}
}

func (m *Api_Response_Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Response_Context.Unmarshal(m, b)
}
func (m *Api_Response_Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Response_Context.Marshal(b, m, deterministic)
}
func (m *Api_Response_Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Response_Context.Merge(m, src)
}
func (m *Api_Response_Context) XXX_Size() int {
	return xxx_messageInfo_Api_Response_Context.Size(m)
}
func (m *Api_Response_Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Response_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Response_Context proto.InternalMessageInfo

func (m *Api_Response_Context) GetErrorMessages() []string {
	if m != nil {
		return m.ErrorMessages
	}
	return nil
}

type Api_Response_InsertProblem struct {
	ProblemId            int64    `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Api_Response_InsertProblem) Reset()         { *m = Api_Response_InsertProblem{} }
func (m *Api_Response_InsertProblem) String() string { return proto.CompactTextString(m) }
func (*Api_Response_InsertProblem) ProtoMessage()    {}
func (*Api_Response_InsertProblem) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 1, 1}
}

func (m *Api_Response_InsertProblem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api_Response_InsertProblem.Unmarshal(m, b)
}
func (m *Api_Response_InsertProblem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api_Response_InsertProblem.Marshal(b, m, deterministic)
}
func (m *Api_Response_InsertProblem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api_Response_InsertProblem.Merge(m, src)
}
func (m *Api_Response_InsertProblem) XXX_Size() int {
	return xxx_messageInfo_Api_Response_InsertProblem.Size(m)
}
func (m *Api_Response_InsertProblem) XXX_DiscardUnknown() {
	xxx_messageInfo_Api_Response_InsertProblem.DiscardUnknown(m)
}

var xxx_messageInfo_Api_Response_InsertProblem proto.InternalMessageInfo

func (m *Api_Response_InsertProblem) GetProblemId() int64 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

func init() {
	proto.RegisterType((*Api)(nil), "pb.Api")
	proto.RegisterType((*Api_Request)(nil), "pb.Api.Request")
	proto.RegisterType((*Api_Request_Context)(nil), "pb.Api.Request.Context")
	proto.RegisterType((*Api_Request_InsertProblem)(nil), "pb.Api.Request.InsertProblem")
	proto.RegisterType((*Api_Response)(nil), "pb.Api.Response")
	proto.RegisterType((*Api_Response_Context)(nil), "pb.Api.Response.Context")
	proto.RegisterType((*Api_Response_InsertProblem)(nil), "pb.Api.Response.InsertProblem")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4a, 0xc4, 0x30,
	0x14, 0xc6, 0xc9, 0x14, 0xac, 0x7d, 0x63, 0x67, 0x91, 0x8d, 0x25, 0x30, 0x32, 0x0a, 0xc2, 0xac,
	0x82, 0xd6, 0x13, 0x0c, 0xea, 0x62, 0x16, 0x8a, 0xe4, 0x02, 0x25, 0xb5, 0x0f, 0x09, 0xd8, 0x24,
	0x26, 0x11, 0xbc, 0x97, 0x27, 0xf0, 0x34, 0x5e, 0x43, 0x48, 0x33, 0xfe, 0x69, 0x71, 0x96, 0xf9,
	0xf2, 0xfb, 0x1e, 0xef, 0xc7, 0x03, 0xe8, 0x64, 0x90, 0xdc, 0x3a, 0x13, 0x0c, 0x9d, 0xd9, 0xf6,
	0xec, 0x3d, 0x83, 0x6c, 0x63, 0x15, 0xfb, 0x20, 0x90, 0x0b, 0x7c, 0x79, 0x45, 0x1f, 0xe8, 0x25,
	0xe4, 0x8f, 0x46, 0x07, 0x7c, 0x0b, 0x15, 0x59, 0x91, 0xf5, 0xbc, 0x3e, 0xe6, 0xb6, 0xe5, 0x1b,
	0xab, 0x78, 0x22, 0xf8, 0xf5, 0xf0, 0x2d, 0x76, 0x1c, 0xbd, 0x81, 0x85, 0xd2, 0x1e, 0x5d, 0x68,
	0xac, 0x33, 0xed, 0x33, 0xf6, 0xd5, 0x2c, 0x36, 0x97, 0xe3, 0xe6, 0x36, 0x52, 0x0f, 0x03, 0x24,
	0x4a, 0xf5, 0xfb, 0xc9, 0x0a, 0xc8, 0xd3, 0x64, 0x56, 0x43, 0xf9, 0x07, 0xa5, 0xa7, 0x70, 0x94,
	0x46, 0x37, 0x5a, 0xf6, 0x18, 0x37, 0x2b, 0xc4, 0x3c, 0x65, 0xf7, 0xb2, 0x47, 0xf6, 0x49, 0xe0,
	0x50, 0xa0, 0xb7, 0x46, 0x7b, 0xa4, 0xf5, 0x58, 0xa2, 0xfa, 0x59, 0x65, 0x40, 0xa6, 0x16, 0xb7,
	0xff, 0x58, 0x9c, 0x4c, 0xaa, 0x7b, 0x35, 0x2e, 0xbe, 0x35, 0xe8, 0x39, 0x2c, 0xd0, 0x39, 0xe3,
	0x9a, 0x1e, 0xbd, 0x97, 0x4f, 0xe8, 0x2b, 0xb2, 0xca, 0xd6, 0x85, 0x28, 0x63, 0x7a, 0x97, 0x42,
	0xc6, 0xc7, 0xb6, 0x4b, 0x80, 0x9d, 0xad, 0xea, 0xa2, 0x40, 0x26, 0x8a, 0x94, 0x6c, 0xbb, 0xf6,
	0x20, 0x1e, 0xf0, 0xea, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x82, 0x92, 0xe6, 0xce, 0x01, 0x00,
	0x00,
}
